"""vote migration

Revision ID: 278574f48ca1
Revises: 3081ef284bf7
Create Date: 2022-06-11 12:35:36.586585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278574f48ca1'
down_revision = '3081ef284bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('win_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='downvotes_user_id_fkey'),
    sa.ForeignKeyConstraint(['win_id'], ['wins.id'], name='downvotes_win_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='downvotes_pkey')
    )
    # ### end Alembic commands ###
