"""profile migration

Revision ID: 54baa9e2d928
Revises: 8a4d19645bb9
Create Date: 2022-06-10 10:16:44.236867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54baa9e2d928'
down_revision = '8a4d19645bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
