"""upvotes migration

Revision ID: 68566f04e81e
Revises: 278574f48ca1
Create Date: 2022-06-14 15:12:57.403121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68566f04e81e'
down_revision = '278574f48ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upvotes', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_column('upvotes', 'comment_id')
    # ### end Alembic commands ###
